---
# Line length - https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md013---line-length
MD013:
  code_blocks: false
  tables: false

# Inline HTML - https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md033
MD033:
