AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  GitHubFullRepositoryName:
    Type: String
    Default: ruzickap/k8s-eks-rancher

Resources:
  Role:
    Type: AWS::IAM::Role
    Properties:
      Description: "Role for running Terrafrom code for GH Actions and local user"
      RoleName: GitHubOidcFederatedRole
      MaxSessionDuration: 36000
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringLike:
                # Allows only actions in this repository to assume the role
                token.actions.githubusercontent.com:sub:
                  - !Sub "repo:${GitHubFullRepositoryName}:*"
            Effect: Allow
            Principal:
              Federated: !Ref GitHubOidc
  GitHubOidc:
    Type: AWS::IAM::OIDCProvider
    Properties:
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        - 6938fd4d98bab03faadb97b34396831e3780aea1
        - 1c58a3a8518e8759bf075b76b750d4f2df264fcd
      Url: https://token.actions.githubusercontent.com

Outputs:
  RoleArn:
    Value: !GetAtt Role.Arn
  GitHubOidcArn:
    Value: !GetAtt GitHubOidc.Arn
