name: mdbook-build-check-deploy

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
    paths:
      - .github/workflows/mdbook-build-check-deploy.yml
      - .markdownlint.yml
      - .spelling
      - docs/**
  push:
    branches:
      - main
    paths:
      - .github/workflows/mdbook-build-check-deploy.yml
      - .markdownlint.yml
      - .spelling
      - docs/**

permissions: read-all

jobs:
  mdbook-build-check-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Install Node.js
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1

      - name: Install markdown-spellcheck
        run: npm install -g markdown-spellcheck

      - name: Run mdspell
        run: find . -type f \( -name "*.md" ! -name "CHANGELOG.md" \) -print0 | xargs -0 --max-args=1 --verbose mdspell --ignore-numbers --ignore-acronyms --report --en-gb

      - uses: jontze/action-mdbook@83b871c38b000c7be415e9773f283786295e29dc # v3.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          use-linkcheck: true
          use-mermaid: false
          use-toc: true
          use-opengh: true

      - name: Build the document
        run: |
          mdbook build ./docs/
          touch ./docs/.nojekyll
          cp LICENSE ./docs/book/
          cp docs/src/README.md docs/book/README.md
          ln -s docs/book ${{ github.event.repository.name }}

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@1f0c5cde4bc74cd7e1254d0cb4de8d49e9068c7d # v4.0.0

      - name: Check broken links
        uses: ruzickap/action-my-broken-link-checker@a0895a4cda23b5c90999cb9d3c8a8f44d8a8980d # v2.5.0
        with:
          url: ${{ steps.pages.outputs.base_url }}
          pages_path: .
          cmd_params: '--buffer-size=8192 --max-connections-per-host=5 --color=always --rate-limit=5 --header="User-Agent:Mozilla" --skip-tls-verification'

      - name: Deploy
        uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847 # v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/book
          force_orphan: true
