---
name: MegaLinter

on:
  workflow_dispatch:
  push:

jobs:
  build:
    name: MegaLinter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Extract commands from markdown files
        run: |
          set -euxo pipefail
          echo '#!/usr/bin/env bash' > README.sh
          find . -name '*.md' -print0 | while IFS= read -r -d '' FILE ; do
            sed -n "/^\`\`\`\(bash\|shell\).*/,/^\`\`\`$/p" "${FILE}" \
            | \
            sed \
              -e 's/^```\(bash\|shell\).*//' \
              -e '/^```$/d' \
            >> README.sh
          done
          chmod a+x README.sh

      - name: MegaLinter
        uses: megalinter/megalinter@v6.18.0
        env:
          BASH_SHFMT_ARGUMENTS: --indent 2 --space-redirects
          DISABLE_LINTERS: CSS_STYLELINT,REPOSITORY_DEVSKIM,REPOSITORY_SEMGREP,SPELL_CSPELL,SPELL_PROSELINT
          SPELL_MISSPELL_ARGUMENTS: -i existant
          FORMATTERS_DISABLE_ERRORS: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRINT_ALPACA: false
          # Needed for scanning generated README.sh file
          VALIDATE_ALL_CODEBASE: true
