name: test-k8s-eks-rancher

on:
  workflow_dispatch:
    inputs:
      action:
        type: choice
        description: Action
        default: create + delete
        options:
          - create
          - delete
          - create + delete
        required: true

env:
  AWS_CONSOLE_ADMIN_ROLE_ARN: ${{ secrets.AWS_CONSOLE_ADMIN_ROLE_ARN }}
  AWS_DEFAULT_REGION: eu-central-1
  AWS_GITHUB_OIDC_FEDERATED_ROLE_TO_ASSUME: ${{ secrets.AWS_GITHUB_OIDC_FEDERATED_ROLE_TO_ASSUME }}
  AWS_USER_ROLE_ARN: ${{ secrets.AWS_USER_ROLE_ARN }}
  MY_PASSWORD: ${{ secrets.MY_PASSWORD }}

permissions:
  id-token: write
  contents: read

concurrency: test-k8s-eks-rancher

jobs:
  k8s-eks-rancher:
    name: "${{ github.event.inputs.action }} | test-k8s-eks-rancher"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: 💡🔪 Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          role-to-assume: ${{ env.AWS_GITHUB_OIDC_FEDERATED_ROLE_TO_ASSUME }}
          role-session-name: GitHubOidcFederatedRole
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Create EKS cluster + environment
        if: ${{ contains(github.event.inputs.action, 'create') }}
        run: |
          ./docker-create-k8s-eks-rancher.sh

      - name: Delete EKS cluster + environment
        if: ${{ contains(github.event.inputs.action, 'delete') }}
        run: |
          ./docker-delete-k8s-eks-rancher.sh
